[build]
workDir = "backend"


[phases.setup]
nixPkgs = ["nodejs", "typescript"]

[phases.install]
cmds = ["npm install --only=production", "npm install --save-dev typescript"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmds = ["npm run start"]
