[build]
workDir = "backend"

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install", "npm install --save-dev typescript","npm install typescript"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmds = ["npm run start"]
