[build]
workDir = "backend"

[phases.setup]
nixPkgs = ["nodejs", "typescript"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmds = ["npm run start"]
